"""Sector definitions for the Nifty RRG.

`SECTOR_INDEX` — sectors Yahoo serves as a real index, with history.
`CONSTITUENTS` — members of every sector, used to drill into a sector and to
rebuild the six sectors Yahoo has no history for.

ponytail: hand-listed, not from an NSE feed — NSE's API 403s server-side
requests. Membership drifts as NSE rebalances; edit here when it does.
"""

SECTOR_INDEX = {
    "BANKNIFTY": "^NSEBANK",
    "SENSEX": "^BSESN",
    "FINNIFTY": "NIFTY_FIN_SERVICE.NS",
    "MIDCAP": "NIFTY_MIDCAP_100.NS",
    "AUTO": "^CNXAUTO",
    "COMMODITIES": "^CNXCMDT",
    "CONSUMPTION": "^CNXCONSUM",
    "ENERGY": "^CNXENERGY",
    "FMCG": "^CNXFMCG",
    "INFRA": "^CNXINFRA",
    "IT": "^CNXIT",
    "MEDIA": "^CNXMEDIA",
    "METAL": "^CNXMETAL",
    "PHARMA": "^CNXPHARMA",
    "PSU BANK": "^CNXPSUBANK",
    "PVT BANK": "NIFTY_PVT_BANK.NS",
    "REALTY": "^CNXREALTY",
    "SERVICES": "^CNXSERVICE",
}

_RAW = {
    "AUTO": "MARUTI M&M TMPV BAJAJ-AUTO EICHERMOT HEROMOTOCO TVSMOTOR ASHOKLEY "
            "BHARATFORG MOTHERSON BOSCHLTD MRF BALKRISIND EXIDEIND TIINDIA",
    "BANKNIFTY": "HDFCBANK ICICIBANK SBIN AXISBANK KOTAKBANK INDUSINDBK BANKBARODA "
                 "PNB CANBK AUBANK FEDERALBNK IDFCFIRSTB",
    "CAPITAL MRKT": "HDFCAMC BSE MCX 360ONE NUVAMA ANGELONE KFINTECH CDSL CAMS "
                    "MOTILALOFS NAM-INDIA IEX ABSLAMC UTIAMC ANANDRATHI",
    "CHEMICALS": "PIDILITIND SRF LINDEINDIA SOLARINDS UPL DEEPAKNTR AARTIIND "
                 "TATACHEM ATUL VINATIORGA NAVINFLUOR FLUOROCHEM PCBL CHAMBLFERT "
                 "COROMANDEL EIDPARRY GNFC BASF SUMICHEM CLEAN",
    "COMMODITIES": "RELIANCE ONGC COALINDIA TATASTEEL JSWSTEEL HINDALCO ULTRACEMCO "
                   "GRASIM VEDL JINDALSTEL ASIANPAINT PIDILITIND SRF UPL AMBUJACEM "
                   "SHREECEM IOC BPCL NMDC HINDZINC",
    "CONSR DURBL": "TITAN HAVELLS DIXON VOLTAS CROMPTON BLUESTARCO KAJARIACER "
                   "BATAINDIA WHIRLPOOL AMBER CERA VGUARD TTKPRESTIG KALYANKJIL "
                   "RAJESHEXPO",
    "CONSUMPTION": "HINDUNILVR ITC MARUTI M&M TITAN BHARTIARTL NESTLEIND TATACONSUM "
                   "BRITANNIA ASIANPAINT TRENT ETERNAL DMART VBL GODREJCP DABUR "
                   "HAVELLS JUBLFOOD INDHOTEL UNITDSPR",
    "DEFENCE": "HAL BEL BDL SOLARINDS MAZDOCK COCHINSHIP GRSE DATAPATTNS ASTRAMICRO "
               "PARAS ZENTEC BEML MTARTECH IDEAFORGE GARFIBRES DYNAMATECH CYIENTDLM "
               "BHARATFORG DCXINDIA UNIMECH",
    "ENERGY": "RELIANCE ONGC NTPC POWERGRID COALINDIA IOC BPCL GAIL ADANIGREEN "
              "TATAPOWER HINDPETRO OIL ATGL NHPC SJVN",
    "FINNIFTY": "HDFCBANK ICICIBANK SBIN AXISBANK KOTAKBANK BAJFINANCE BAJAJFINSV "
                "SHRIRAMFIN JIOFIN SBILIFE HDFCLIFE HDFCAMC ICICIGI ICICIPRULI "
                "CHOLAFIN MUTHOOTFIN LICHSGFIN PFC RECLTD SBICARD",
    "FMCG": "HINDUNILVR ITC NESTLEIND TATACONSUM BRITANNIA GODREJCP DABUR MARICO "
            "COLPAL VBL UNITDSPR RADICO EMAMILTD PGHH BALRAMCHIN",
    "HEALTHCARE": "SUNPHARMA DIVISLAB CIPLA TORNTPHARM DRREDDY APOLLOHOSP MAXHEALTH "
                  "LUPIN ZYDUSLIFE MANKIND AUROPHARMA FORTIS ALKEM ABBOTINDIA "
                  "GLENMARK LAURUSLABS BIOCON GRANULES SYNGENE IPCALAB",
    "INFRA": "LT RELIANCE BHARTIARTL NTPC POWERGRID ONGC ULTRACEMCO GRASIM "
             "ADANIPORTS SIEMENS ABB BEL HAL IRCTC GMRAIRPORT CONCOR INDUSTOWER "
             "AMBUJACEM SHREECEM ACC",
    "IT": "TCS INFY HCLTECH WIPRO TECHM LTIM PERSISTENT COFORGE MPHASIS OFSS",
    "MEDIA": "ZEEL SUNTV PVRINOX NAZARA TIPSMUSIC SAREGAMA DISHTV NETWORK18 "
             "TV18BRDCST HATHWAY",
    "METAL": "TATASTEEL JSWSTEEL HINDALCO VEDL JINDALSTEL SAIL NMDC NATIONALUM "
             "HINDZINC APLAPOLLO JSL WELCORP HINDCOPPER RATNAMANI LLOYDSME",
    "MIDCAP": "MAXHEALTH PERSISTENT COFORGE INDHOTEL POLYCAB DIXON MUTHOOTFIN LUPIN "
              "GODREJPROP VOLTAS PHOENIXLTD SUZLON BHARATFORG MRF ASHOKLEY PAGEIND "
              "AUBANK FEDERALBNK ALKEM SUPREMEIND",
    "OIL & GAS": "RELIANCE ONGC IOC BPCL GAIL HINDPETRO ATGL OIL PETRONET IGL MGL "
                 "CASTROLIND AEGISLOG",
    "PHARMA": "SUNPHARMA DIVISLAB CIPLA TORNTPHARM DRREDDY LUPIN ZYDUSLIFE MANKIND "
              "AUROPHARMA ALKEM GLENMARK LAURUSLABS BIOCON GRANULES IPCALAB "
              "ABBOTINDIA JBCHEPHARM NATCOPHARM AJANTPHARM SANOFI",
    "PSU BANK": "SBIN BANKBARODA PNB CANBK UNIONBANK INDIANB BANKINDIA CENTRALBK "
                "IOB UCOBANK MAHABANK PSB",
    "PVT BANK": "HDFCBANK ICICIBANK AXISBANK KOTAKBANK INDUSINDBK FEDERALBNK "
                "IDFCFIRSTB BANDHANBNK RBLBANK AUBANK",
    "REALTY": "DLF GODREJPROP OBEROIRLTY PRESTIGE PHOENIXLTD BRIGADE SOBHA ANANTRAJ "
              "MAHLIFE SIGNATURE",
    "SENSEX": "RELIANCE HDFCBANK ICICIBANK INFY TCS ITC BHARTIARTL SBIN LT AXISBANK "
              "KOTAKBANK HINDUNILVR M&M MARUTI SUNPHARMA NTPC TITAN ULTRACEMCO "
              "ASIANPAINT BAJFINANCE BAJAJFINSV NESTLEIND POWERGRID TATASTEEL TECHM "
              "HCLTECH ADANIPORTS TMPV INDUSINDBK ETERNAL",
    "SERVICES": "HDFCBANK ICICIBANK TCS INFY BHARTIARTL SBIN AXISBANK KOTAKBANK "
                "HCLTECH BAJFINANCE ADANIPORTS INDIGO DMART APOLLOHOSP TRENT "
                "ETERNAL IRCTC CONCOR HDFCLIFE SBILIFE",
}

# Symbols with no usable Yahoo history — pruned so baskets stay clean.
# TV18BRDCST merged into NETWORK18 (already listed); LTIM has no Yahoo symbol.
NO_YAHOO_HISTORY = {"GSPL", "GUJGASLTD", "ADANITOTAL", "LTIM", "TV18BRDCST"}

CONSTITUENTS = {k: [t for t in v.split() if t not in NO_YAHOO_HISTORY]
                for k, v in _RAW.items()}
SECTORS = sorted(CONSTITUENTS)
BASKET_SECTORS = [s for s in SECTORS if s not in SECTOR_INDEX]
